Add: Added homepage to Video library
zoef-yt/game-plex-react pull request #1
Opened 2022-04-13 22:14 UTC by zoef-yt

In this Pr, I added a Homepage to my video library.

2022-04-14 03:17 UTC, Muzammil-khan710 approved these changes
UI is really great Zoef !
Code structure is good
Good to merge

2022-04-14 04:20 UTC, iRohitGaur approved these changes
Nice work!

Code is easy to understand.

Good to merge 👍🏻

2022-04-14 08:56 UTC, bhushannaikaroskar approved these changes
Hey zoef, reviewed your code. Loved your UI and animations. I have given some minor suggestion do check. Approving your merge

2022-04-14 08:56 UTC, bhushannaikaroskar commented on src/Pages/Home/Home.css
> +	}
Maybe you can use just 0 instead of 0rem.

2022-04-14 08:56 UTC, bhushannaikaroskar commented on src/Pages/Components/Navbar/Navbar.jsx
> +							<li>Logout 😞</li>
I would suggestion to remove the <hr/> tag. It works the same even without <hr/> tag

2022-04-16 05:59 UTC, zoef-yt commented on src/Pages/Home/Home.css
> +	}
Done.

2022-04-16 06:01 UTC, zoef-yt commented on src/Pages/Components/Navbar/Navbar.jsx
> +							<li>Logout 😞</li>
I think Github markdown computed your `<hr>` tag but I got your point. 

With `<hr>` tag.
> ![image](https://user-images.githubusercontent.com/67889207/163663770-5ba9bea4-813a-4a12-89f9-ad9bffb8d2ad.png)

Without `<hr>` tag
> ![image](https://user-images.githubusercontent.com/67889207/163663792-36b44e7a-2f50-4ed7-be3f-2012b81966b5.png)

2022-04-16 10:45 UTC, muskanbagrecha requested changes
Great work. Do look into the suggested changes.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Components/Footer/Footer.jsx
> +function Footer() {
Use arrow functions.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Components/Navbar/Navbar.css
> +	width: 100%;
Suggestion: I don't think width is required here.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Components/Navbar/Navbar.css
> +	width: 100%;
Can remove width here as well.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Components/Navbar/Navbar.jsx
> +import React from 'react';
import not required here.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Components/Navbar/Navbar.jsx
> +		<nav className='navbar-mobile'>
I think you can use a better name than navbar-mobile as it is ambiguous.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Components/Navbar/Navbar.jsx
> +						<div className='profile-modal'>
Extract the profile modal.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Home/Home.css
> +	transition: all 0.3s ease;
You are using transition for every child so you can check if applying it to the parent will be sufficient as it gets too repititive.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Home/Home.css
> +		z-index: 5;
You could use variables for z-index.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Home/Home.jsx
> +					<div className='category-card'>
Extract this into a component.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/index.css
> +		'footer  ';
Remove the trailing spaces.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/Pages/Home/Home.jsx
> +					</div>
Fetch the data using the api.

2022-04-16 10:45 UTC, muskanbagrecha commented on src/index.css
> +			'main-content '
Remove trailing spaces.

2022-04-16 12:00 UTC, zoef-yt commented on src/Pages/Components/Footer/Footer.jsx
> +function Footer() {
done.

2022-04-16 12:00 UTC, zoef-yt commented on src/Pages/Components/Navbar/Navbar.css
> +	width: 100%;
removed.

2022-04-16 12:01 UTC, zoef-yt commented on src/Pages/Components/Navbar/Navbar.css
> +	width: 100%;
removed.

2022-04-16 12:02 UTC, zoef-yt commented on src/Pages/Components/Navbar/Navbar.jsx
> +import React from 'react';
removed.

2022-04-16 12:02 UTC, zoef-yt commented on src/Pages/Components/Navbar/Navbar.jsx
> +		<nav className='navbar-mobile'>
Will be changing this in future refractor

2022-04-16 12:03 UTC, zoef-yt commented on src/Pages/Components/Navbar/Navbar.jsx
> +						<div className='profile-modal'>
Done.

2022-04-16 12:04 UTC, zoef-yt commented on src/Pages/Home/Home.jsx
> +					<div className='category-card'>
Done.

2022-04-16 12:04 UTC, zoef-yt commented on src/index.css
> +		'footer  ';
Done.

2022-04-16 12:04 UTC, zoef-yt commented on src/Pages/Home/Home.jsx
> +					</div>
Done.

2022-04-16 12:05 UTC, zoef-yt commented on src/Pages/Home/Home.css
> +		z-index: 5;
Will be doing it in PR #4

2022-04-16 12:05 UTC, zoef-yt commented on src/index.css
> +			'main-content '
done.

2022-04-16 12:07 UTC, zoef-yt commented on src/Pages/Home/Home.css
> +	transition: all 0.3s ease;
I tried but it won't work like that.

2022-04-16 12:07 UTC, zoef-yt commented
@muskanbagrecha did all the mentioned suggestions on pr #3

2022-04-16 12:16 UTC, muskanbagrecha approved these changes
Good to merge as you have implemented the suggested changes. Great animations and layout looks perfect on the listing page.

2022-04-16 12:25 UTC, merged