Video listing page layout
zoef-yt/game-plex-react pull request #2
Opened 2022-04-14 21:01 UTC by zoef-yt

In this pr, I added explore page with the category selection bar. The app is mobile-first so you can check it on any screen. There is a little animation on the hover of the video card and the card has a shadow in light theme.

[Files to check]()

2022-04-15 04:31 UTC, zoyatanweer commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	max-width: 1560px;
use rem

2022-04-15 04:33 UTC, srishtigautam21 commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	perspective: 400px;
use rem

2022-04-15 04:33 UTC, srishtigautam21 approved these changes
clean code
good to merge with changes

2022-04-15 04:42 UTC, zoyatanweer approved these changes
- code looks great and is easy to understand

- few suggestion in UI : 
      1. you can make the first video which is on display in the homepage less wider, maybe make it the same width as the featured categories(from start to end). This will make the page look more uniform.
      2. When hovering on the featured categories, the cursor is in pointer when hovered on the "watch now" section. You can make the cursor as pointer on the whole video so the user doesn't has to specifically click on "watch now".
      
Appreciation: Love the animation . Great UI .

-good to merge

2022-04-16 11:28 UTC, muskanbagrecha requested changes
Great work. Do look into the suggested changes.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Context/CategoryContext/CategoryContext.jsx
> +const CategoryContext = createContext();
You can give an empty array as the initial value.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Context/CategoryContext/CategoryContext.jsx
> +	const [categories, setCategories] = useState('');
You can use an empty array as the initial value.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Context/CategoryContext/CategoryContext.jsx
> +		if (categoriesResponse?.categories) {
Can you ternary.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Context/VideoContext/VideoContext.jsx
> +	const [videos, setVideos] = useState('');
Empty array as the initial value.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Context/VideoContext/VideoContext.jsx
> +const VideoContext = createContext();
Empty array as the initial value.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Context/VideoContext/VideoContext.jsx
> +		if (videosResponse?.videos) {
ternary

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Pages/PageNotFound/PageNotFound.jsx
> +function PageNotFound() {
Arrow function.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	border-radius: 0.5rem;
You can use px in border radius

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	transform: rotateY(-120deg);
Appreciation: great hover effect.

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	perspective: 400px;
Appreciation: Great use of perspective

2022-04-16 11:28 UTC, muskanbagrecha commented on src/Pages/VideoListingPage/components/CategorySelectionBar.css
> +	top: 0rem;
Remove rem.

2022-04-16 11:40 UTC, zoef-yt commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	perspective: 400px;
done

2022-04-16 11:40 UTC, zoef-yt commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	max-width: 1560px;
done

2022-04-16 12:10 UTC, zoef-yt commented on src/Context/CategoryContext/CategoryContext.jsx
> +const CategoryContext = createContext();
done.

2022-04-16 12:10 UTC, zoef-yt commented on src/Context/CategoryContext/CategoryContext.jsx
> +	const [categories, setCategories] = useState('');
done.

2022-04-16 12:11 UTC, zoef-yt commented on src/Context/CategoryContext/CategoryContext.jsx
> +		if (categoriesResponse?.categories) {
done.

2022-04-16 12:11 UTC, zoef-yt commented on src/Context/VideoContext/VideoContext.jsx
> +	const [videos, setVideos] = useState('');
done.

2022-04-16 12:11 UTC, zoef-yt commented on src/Context/VideoContext/VideoContext.jsx
> +const VideoContext = createContext();
done.

2022-04-16 12:11 UTC, zoef-yt commented on src/Context/VideoContext/VideoContext.jsx
> +		if (videosResponse?.videos) {
done.

2022-04-16 12:12 UTC, zoef-yt commented on src/Pages/PageNotFound/PageNotFound.jsx
> +function PageNotFound() {
done.

2022-04-16 12:12 UTC, zoef-yt commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	border-radius: 0.5rem;
done.

2022-04-16 12:13 UTC, zoef-yt commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	transform: rotateY(-120deg);
Thanks.

2022-04-16 12:13 UTC, zoef-yt commented on src/Pages/VideoListingPage/VideoListingPage.css
> +	perspective: 400px;
Thanks

2022-04-16 12:13 UTC, zoef-yt commented on src/Pages/VideoListingPage/components/CategorySelectionBar.css
> +	top: 0rem;
done.

2022-04-16 12:15 UTC, zoef-yt commented
> * code looks great and is easy to understand
> * few suggestion in UI :
>   1. you can make the first video which is on display in the homepage less wider, maybe make it the same width as the featured categories(from start to end). This will make the page look more uniform.
>   2. When hovering on the featured categories, the cursor is in pointer when hovered on the "watch now" section. You can make the cursor as pointer on the whole video so the user doesn't has to specifically click on "watch now".
> 
> Appreciation: Love the animation . Great UI .
> 
> -good to merge

Thanks for the suggestion will look into it.

2022-04-16 12:15 UTC, zoef-yt commented
@muskanbagrecha did all the suggested changes in #3.

2022-04-17 13:10 UTC, muskanbagrecha commented
Good to merge as all the changes have been made in the next PR. Overall, love the UI and lots to learn from your animation effects. Simply brilliant. Great work on the layout of the listing page as it looks good on all screens.

2022-04-17 19:12 UTC, muskanbagrecha approved these changes
Good to merge as all the changes have been made in the next PR. Overall, love the UI and lots to learn from your animation effects. Simply brilliant. Great work on the layout of the listing page as it looks good on all screens.

2022-04-17 19:14 UTC, merged