Playlist management
zoef-yt/game-plex-react pull request #8
Opened 2022-04-27 22:31 UTC by zoef-yt

[PREVIEW LINK]()
[CHECK ME ONLY]()
In this PR, I added 
- Playlist management and UI for playlist page.

2022-04-28 02:44 UTC, iRohitGaur commented on src/Context/HistoryContext/HistoryContext.jsx
> +		console.log(historyError?.response);
suggestion: remove `console.log`

2022-04-28 02:45 UTC, iRohitGaur approved these changes
Good work!

UI looks nice. Good to merge 👍🏻

2022-04-28 16:52 UTC, santhoshpemmaka commented
No suggestions from my side. Great Work 💯 .

UI looks great. Good to merge 👍 .

2022-04-28 16:52 UTC, santhoshpemmaka approved these changes

2022-05-21 10:13 UTC, muskanbagrecha requested changes
Code looks good. Please look into the suggested changes.

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Context/PlaylistContext/PlaylistContext.jsx
> +		if (playlistResponse != null && playlistResponse.playlists) {
Can use optional chaining

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Context/PlaylistContext/PlaylistContext.jsx
> +		if (playlistResponse != null && playlistResponse.playlist) {
Can use OC.

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Context/PlaylistContext/PlaylistContext.jsx
> +			const updatedPlaylists = playlists.playlists.map((playlist) => {
This line of code is difficult to read.

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Pages/Components/Modal/ModalContent/PlaylistModalComponent.jsx
> +		playlistTitle.length > 1
Can avoid using ternary when there is nesting in future projects. It makes it easier to read for reviewers.

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Pages/Components/Modal/ModalContent/PlaylistModalComponent.jsx
> +			{currentVideo != null && (
Strict checking

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Pages/Components/Modal/ModalContent/PlaylistModalComponent.jsx
> +				{playlistTitle.length < 1 && <p>*TextField cannot be empty</p>}
The problem with this is even when the user has just begun typing the error shows up.

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Pages/PlayListPage/PlaylistPage.jsx
> +					{playlists?.playlists != null &&
You can use OC.

2022-05-21 10:13 UTC, muskanbagrecha commented on src/Pages/PlayListPage/PlaylistPage.jsx
> +			{playlists.playlists === null || playlists.playlists.length < 1 ? (
You can make this line shorter.

2022-05-21 10:48 UTC, zoef-yt commented on src/Context/PlaylistContext/PlaylistContext.jsx
> +		if (playlistResponse != null && playlistResponse.playlists) {
done

2022-05-21 11:13 UTC, muskanbagrecha approved these changes
Great work on VL. Animations look superb. Good to merge.

2022-05-21 11:13 UTC, merged